---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/12/6 16:48
---
i =10000
print(i)
print("打印数据类型")
print(type(110))
print(type(4.64))
print(type('string'))
print(type({x, 1}, {y, 2}))
function func1(arg)
    x = 123             -- 全局变量
    local y = 789       -- 局部变量
    print(arg)
end
print(type(func1))

func1(10)               -- 必须有调用，x才能生效！
print("x=", x)
print("y=", y)
